# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-26 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trips',
            new_name='Trip',
        ),
        migrations.AlterField(
            model_name='user',
            name='startdate',
            field=models.DateField(verbose_name='%m/%d/%Y'),
        ),
    ]
